[project]
name = "test-algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pyceres>=2.6",
    "pygame>=2.6.1",
    "scipy>=1.17.0",
]
